# Generated by Django 2.2.5 on 2019-10-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='project',
        ),
        migrations.AddField(
            model_name='applications',
            name='project',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Project'),
        ),
    ]
