# Generated by Django 2.2.5 on 2019-10-03 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='relation',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
