# Generated by Django 2.2.5 on 2019-10-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191003_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskills',
            name='relation',
        ),
        migrations.AddField(
            model_name='user_details',
            name='skills',
            field=models.ManyToManyField(blank=True, to='account.UserSkills'),
        ),
    ]
