# Generated by Django 2.2.5 on 2019-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191003_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_skill',
            field=models.ManyToManyField(blank=True, to='account.UserSkills'),
        ),
    ]
