# Generated by Django 2.2.5 on 2019-10-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='PositionModel',
        ),
    ]
