# Generated by Django 2.2.5 on 2019-10-07 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191004_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='account.PositionModel'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
