# Generated by Django 2.2.5 on 2019-10-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20191007_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='position',
        ),
    ]
